ctf:
  name: "PETIR CTF 2025"
  description: |
    Welcome to the PETIR CTF 2025!
    This Capture The Flag competition is designed to test your cybersecurity skills across various domains.
    Solve challenges, find flags, and compete with teams from around the world.
    The event features challenges in web exploitation, cryptography, reverse engineering, forensics, and more.
  location: "Online"
  start_time: "01-06-2025 12:00" # Format: dd-mm-yyyy hh:mm
  end_time: "03-07-2025 15:00"
  # (look for your timezone at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
  time_zone: "Asia/Jakarta" # Base timezone
  convert_to_time_zone: "Asia/Jakarta" # Display/converted timezone

credentials:
  admin_username: admin
  admin_email: petir@petir.com
  admin_password: abcdefgabcedfgABCEDFGABCEDFG12309321@#!@#
