version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: softeng_frontend
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: softeng_backend
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: softeng_nginx
    ports:
      - "9999:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: softeng_db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]

volumes:
  postgres_data:
