version: "3.8"

services:
  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: react_frontend
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   depends_on:
  #     - backend

  backend:
    build: ./backend
    container_name: softeng_backend
    volumes:
      - ./backend:/app
    # depends_on:
    #   - db

  nginx:
    image: nginx:latest
    container_name: softeng_nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      # - frontend
      - backend

  # db:
  #   image: postgres:13
  #   container_name: postgres_db
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_DB=app_db
  #     - POSTGRES_USER=app_user
  #     - POSTGRES_PASSWORD=app_pass
