version: "3.8"

services:
  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: react_frontend
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   depends_on:
  #     - backend

  backend:
    build: ./backend
    container_name: softeng_backend
    environment:
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: softeng_nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      # - frontend
      - backend

  db:
    image: postgres:14
    container_name: softeng_db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

volumes:
  postgres_data:
